---
name: ci

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - release-*
  # Run tests for PRs
  pull_request:
    branches:
      - main
      - release-*
env:
  PRE_RELEASE: ${{ github.ref == 'refs/heads/main' && 'development' || '' }}
  GO_LANGCI_LINT_VER: "v2.13.1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - 
        name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      -
        name: Test Setup
        run: |
          make install-gotestsum
      -
        name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ env.GO_LANGCI_LINT_VER }}
          args: --timeout=30m
      -
        name: Test
        run: |
          .ext/bin/gotestsum --format short-verbose -- -count=1 -parallel=1 -v -timeout=240s -coverprofile=cover.out -coverpkg=./... ./...
      -
        name: Upload code coverage
        uses: shogo82148/actions-goveralls@v1
        continue-on-error: true
        with:
          path-to-profile: cover.out
